---
title: "BC tools"
author: "Aleš Saska <mail@alessaska.cz>"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# bctools package

This package contains pretty printer for R language Bytecode. It can be used for debugging purposes and for code analysis. It defines print method for bytecode object ( which is used internally by R language ).

Print function support 3 levels of verbosity ( parameter verbose=0/1/2 ).

* verbose=0 - Print only source references ( if they are available )
* verbose=1 - Print both source and expression references ( if they are available ) and also print bytecode version
* verbose=2 - Print all operands' arguments ( including ones used just for debugging )

## Output description

* labels starts with 1:, 2: ... ( references to them begins with $ - $1 / $2 ... ).
* expression references begins with @
* source references with # ( if you want to be sure there are source references in bytecode included, call options(keep.source = TRUE) )

## Examples

This is short example how to use the print method for bytecode object.

```{r}

library(compiler)
library(bctools)

f <- function(x){
    sum <- 0
    while(x > 0){
        sum <- sum + x
    }
    sum
}

bytecode <- compiler::cmpfun(f);

print(compiler::disassemble(bytecode));


```
